In [1]:
# %pip install -r requirements.txt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

import kmrf as kmrf

%matplotlib inline

In [2]:
# # Load and retrain each saved model with adjusted train/val/test dates and set raw data, and save the updated model
# for classification_dir in ['adapted', 'original']:

#     for asset_class_dir in ['us_equity', 'commodity']:
#         saved_models_dir = Path(f'saved_models/KMRF/{classification_dir}_labels/{asset_class_dir}')
#         saved_models_list = sorted(list(saved_models_dir.glob('*.pkl')))

#         for i in range(len(saved_models_list)):
#             print(f"\nLoading and retraining model index = {i}: {saved_models_list[i].name}\n")
#             kmrf_model = kmrf.KMRF.load_model(saved_models_list[i])
#             kmrf_model.set_raw_data()
#             kmrf_model.adjust_train_val_test_dates(val_start='2019-04-01', val_end='2021-09-30',
#                                         test_start='2021-11-01', test_end='2025-10-24')
#             kmrf_model.fit()
#             kmrf_model.save_model(boruta_used=True)

In [3]:
classification_dir = 'adapted'  # Specify the classification directory here
asset_class_dir = 'commodity'    # Specify the asset class directory here

In [4]:
# List available saved KMRF models for specified classification and asset class
saved_models_dir = Path(f'saved_models/KMRF/{classification_dir}_labels/{asset_class_dir}')

if saved_models_dir.exists():
    saved_models_list = list(saved_models_dir.glob('*.pkl'))

    if saved_models_list:
        saved_models_list = sorted(saved_models_list)
        print(f"Available saved models in '{saved_models_dir}':\n")
        for i, model_path in enumerate(saved_models_list):
            print(f" index = {i}: {model_path.name}")
    else:
        print(f"No saved models found in '{saved_models_dir}'. Train a model first!")

Available saved models in 'saved_models/KMRF/adapted_labels/commodity':

 index = 0: KMRF_Brent-Crude-Oil_20190101_boruta.pkl
 index = 1: KMRF_Coffee_20190101_boruta.pkl
 index = 2: KMRF_Copper_20190101_boruta.pkl
 index = 3: KMRF_Corn-Futures_20190101_boruta.pkl
 index = 4: KMRF_Gold-Futures_20190101_boruta.pkl
 index = 5: KMRF_Live-Cattle-Futures_20190101_boruta.pkl
 index = 6: KMRF_Natural-Gas_20190101_boruta.pkl
 index = 7: KMRF_Soybean-Futures_20190101_boruta.pkl
 index = 8: KMRF_Sugar_20190101_boruta.pkl
 index = 9: KMRF_Wheat-Futures_20190101_boruta.pkl

In [5]:
kmrf_model = kmrf.KMRF.load_model(saved_models_list[4])
display(kmrf_model)
kmrf_model.predict(test_or_val='val')
# kmrf_model.set_raw_ohlc()
kmrf_model.viz_predictions(test_or_val='val')

KMRF model initialized
  Asset: Gold Futures
  Asset class: commodity
  Classification type: adapted
  End date: 20190101
  Using pre-computed features: True
  Data path: data/ready/commodity.csv
  KAMA+MSR model directory: saved_models/KAMA_MSR/commodity/20190101
  Validation period: 2019-02-01 00:00:00 to 2021-12-30 00:00:00
  Test start: 2022-02-01 00:00:00
  Random seed: 1010

KMRF('commodity, Gold Futures')
Raw Price Data (10945, 69): 1990-01-01 to 2025-10-24
Train (5840, 53): 1996-01-05 to 2018-12-31
Val (896, 53): 2019-02-01 to 2021-12-30
Test (1097, 53): 2022-02-01 to 2025-10-24

Generating predictions...
  Input shape: (896, 53)
  Using pre-selected features: 53
✓ Generated probability predictions: (896, 3)

KeyError: "[Timestamp('2019-02-03 00:00:00'), Timestamp('2019-02-10 00:00:00'), Timestamp('2019-02-24 00:00:00'), Timestamp('2019-03-03 00:00:00'), Timestamp('2019-03-10 00:00:00'), Timestamp('2019-03-17 00:00:00'), Timestamp('2019-03-24 00:00:00'), Timestamp('2019-03-31 00:00:00'), Timestamp('2019-04-07 00:00:00'), Timestamp('2019-04-14 00:00:00'), Timestamp('2019-04-21 00:00:00'), Timestamp('2019-04-28 00:00:00'), Timestamp('2019-05-05 00:00:00'), Timestamp('2019-05-12 00:00:00'), Timestamp('2019-05-19 00:00:00'), Timestamp('2019-06-02 00:00:00'), Timestamp('2019-06-09 00:00:00'), Timestamp('2019-06-16 00:00:00'), Timestamp('2019-06-23 00:00:00'), Timestamp('2019-06-30 00:00:00'), Timestamp('2019-07-07 00:00:00'), Timestamp('2019-07-14 00:00:00'), Timestamp('2019-07-21 00:00:00'), Timestamp('2019-07-28 00:00:00'), Timestamp('2019-08-04 00:00:00'), Timestamp('2019-08-11 00:00:00'), Timestamp('2019-08-18 00:00:00'), Timestamp('2019-08-25 00:00:00'), Timestamp('2019-09-08 00:00:00'), Timestamp('2019-09-15 00:00:00'), Timestamp('2019-09-22 00:00:00'), Timestamp('2019-09-29 00:00:00'), Timestamp('2019-10-06 00:00:00'), Timestamp('2019-10-13 00:00:00'), Timestamp('2019-10-20 00:00:00'), Timestamp('2019-10-27 00:00:00'), Timestamp('2019-11-03 00:00:00'), Timestamp('2019-11-10 00:00:00'), Timestamp('2019-11-17 00:00:00'), Timestamp('2019-11-24 00:00:00'), Timestamp('2019-12-01 00:00:00'), Timestamp('2019-12-08 00:00:00'), Timestamp('2019-12-15 00:00:00'), Timestamp('2019-12-22 00:00:00'), Timestamp('2019-12-25 00:00:00'), Timestamp('2019-12-29 00:00:00'), Timestamp('2020-01-01 00:00:00'), Timestamp('2020-01-05 00:00:00'), Timestamp('2020-01-12 00:00:00'), Timestamp('2020-01-26 00:00:00'), Timestamp('2020-02-02 00:00:00'), Timestamp('2020-02-09 00:00:00'), Timestamp('2020-02-23 00:00:00'), Timestamp('2020-03-01 00:00:00'), Timestamp('2020-03-08 00:00:00'), Timestamp('2020-03-15 00:00:00'), Timestamp('2020-03-22 00:00:00'), Timestamp('2020-03-29 00:00:00'), Timestamp('2020-04-05 00:00:00'), Timestamp('2020-04-12 00:00:00'), Timestamp('2020-04-19 00:00:00'), Timestamp('2020-04-26 00:00:00'), Timestamp('2020-05-03 00:00:00'), Timestamp('2020-05-10 00:00:00'), Timestamp('2020-05-17 00:00:00'), Timestamp('2020-05-31 00:00:00'), Timestamp('2020-06-07 00:00:00'), Timestamp('2020-06-14 00:00:00'), Timestamp('2020-06-21 00:00:00'), Timestamp('2020-06-28 00:00:00'), Timestamp('2020-07-05 00:00:00'), Timestamp('2020-07-12 00:00:00'), Timestamp('2020-07-19 00:00:00'), Timestamp('2020-07-26 00:00:00'), Timestamp('2020-08-02 00:00:00'), Timestamp('2020-08-09 00:00:00'), Timestamp('2020-08-16 00:00:00'), Timestamp('2020-08-23 00:00:00'), Timestamp('2020-08-30 00:00:00'), Timestamp('2020-09-13 00:00:00'), Timestamp('2020-09-20 00:00:00'), Timestamp('2020-09-27 00:00:00'), Timestamp('2020-10-04 00:00:00'), Timestamp('2020-10-11 00:00:00'), Timestamp('2020-10-18 00:00:00'), Timestamp('2020-10-25 00:00:00'), Timestamp('2020-11-01 00:00:00'), Timestamp('2020-11-08 00:00:00'), Timestamp('2020-11-15 00:00:00'), Timestamp('2020-11-22 00:00:00'), Timestamp('2020-11-29 00:00:00'), Timestamp('2020-12-06 00:00:00'), Timestamp('2020-12-13 00:00:00'), Timestamp('2020-12-20 00:00:00'), Timestamp('2020-12-27 00:00:00'), Timestamp('2021-01-03 00:00:00'), Timestamp('2021-01-10 00:00:00'), Timestamp('2021-01-24 00:00:00'), Timestamp('2021-01-31 00:00:00'), Timestamp('2021-02-07 00:00:00'), Timestamp('2021-02-21 00:00:00'), Timestamp('2021-02-28 00:00:00'), Timestamp('2021-03-07 00:00:00'), Timestamp('2021-03-14 00:00:00'), Timestamp('2021-03-21 00:00:00'), Timestamp('2021-03-28 00:00:00'), Timestamp('2021-04-02 00:00:00'), Timestamp('2021-04-04 00:00:00'), Timestamp('2021-04-11 00:00:00'), Timestamp('2021-04-18 00:00:00'), Timestamp('2021-04-25 00:00:00'), Timestamp('2021-05-02 00:00:00'), Timestamp('2021-05-09 00:00:00'), Timestamp('2021-05-16 00:00:00'), Timestamp('2021-05-23 00:00:00'), Timestamp('2021-06-06 00:00:00'), Timestamp('2021-06-13 00:00:00'), Timestamp('2021-06-20 00:00:00'), Timestamp('2021-06-27 00:00:00'), Timestamp('2021-07-11 00:00:00'), Timestamp('2021-07-18 00:00:00'), Timestamp('2021-07-25 00:00:00'), Timestamp('2021-08-01 00:00:00'), Timestamp('2021-08-08 00:00:00'), Timestamp('2021-08-15 00:00:00'), Timestamp('2021-08-22 00:00:00'), Timestamp('2021-08-29 00:00:00'), Timestamp('2021-09-12 00:00:00'), Timestamp('2021-09-19 00:00:00'), Timestamp('2021-09-26 00:00:00'), Timestamp('2021-10-03 00:00:00'), Timestamp('2021-10-10 00:00:00'), Timestamp('2021-10-17 00:00:00'), Timestamp('2021-10-24 00:00:00'), Timestamp('2021-10-31 00:00:00'), Timestamp('2021-11-07 00:00:00'), Timestamp('2021-11-14 00:00:00'), Timestamp('2021-11-21 00:00:00'), Timestamp('2021-11-27 00:00:00'), Timestamp('2021-11-28 00:00:00'), Timestamp('2021-12-05 00:00:00'), Timestamp('2021-12-12 00:00:00'), Timestamp('2021-12-19 00:00:00'), Timestamp('2021-12-26 00:00:00')] not in index"

In [10]:
kmrf_model.raw_ohlc.loc['2019-02-01':'2019-04-30']

           Gold Futures
                   open    high     low   close
date
2019-02-01       1326.0  1328.2  1320.6  1322.1
2019-02-04       1322.6  1323.6  1312.7  1319.3
2019-02-05       1316.8  1321.0  1314.8  1319.2
2019-02-06       1319.4  1319.9  1309.6  1314.4
2019-02-07       1310.9  1315.8  1306.4  1314.2
...                 ...     ...     ...     ...
2019-04-24       1274.4  1280.7  1270.5  1279.4
2019-04-25       1277.9  1284.8  1275.2  1279.7
2019-04-26       1279.1  1290.9  1276.0  1288.8
2019-04-29       1289.0  1289.1  1279.9  1281.5
2019-04-30       1281.9  1288.2  1281.5  1285.7

[62 rows x 4 columns]

In [9]:
kmrf_model.features.loc['2019-02-01':'2019-04-30']

,open,open_lag1d,high_lag1d,low_lag1d,close_lag1d,log_ret_overnight,log_ret_intraday_lag1d,log_ret_lag1d,log_ret_5d_lag1d,log_ret_10d_lag1d,...,skew_60d_lag1d,kurt_60d_lag1d,var_95_60d_lag1d,var_99_60d_lag1d,skew_120d_lag1d,kurt_120d_lag1d,var_95_120d_lag1d,var_99_120d_lag1d,drawdown_lag1d,max_drawdown_1y_lag1d
date,,,,,,,,,,,,,,,,,,,,,
2019-02-01,1326.0,1325.4,1331.1,1322.2,1325.2,0.000604,-0.000151,0.007347,0.020662,0.032674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.395871,-0.4507
2019-02-03,NaN,1326.0,1328.2,1320.6,1322.1,NaN,-0.002946,-0.002342,NaN,0.029709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.397284,-0.4507
2019-02-04,1322.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.397284,-0.4507
2019-02-05,1316.8,1322.6,1323.6,1312.7,1319.3,-0.001897,-0.002498,NaN,0.007914,0.027121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.397284,-0.4507
2019-02-06,1319.4,1316.8,1321.0,1314.8,1319.2,0.000152,0.001821,-0.000076,0.002809,0.030322,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.397330,-0.4507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-25,1277.9,1274.4,1280.7,1270.5,1279.4,-0.001173,0.003916,0.004858,0.002034,-0.010806,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.405871,-0.4507
2019-04-26,1279.1,1277.9,1284.8,1275.2,1279.7,-0.000469,0.001408,0.000234,0.002895,-0.012039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.405732,-0.4507
2019-04-28,NaN,1279.1,1290.9,1276.0,1288.8,NaN,0.007555,0.007086,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.401506,-0.4507
2019-04-29,1289.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.401506,-0.4507
2019-04-30,1281.9,1289.0,1289.1,1279.9,1281.5,0.000312,-0.005835,NaN,0.006498,0.003361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.401506,-0.4507